idf_component_register(
    SRCS
        "src/main.c"
        "src/utils.c"
        "src/task_spi_usb.c"
        "src/gamepad_hid.c"
        "src/hid_parsing.c"
        "src/webserver.c"
        "src/task_webhost.c"
        "src/programming_mode.c"
        "src/W25Q128J.c"
        "src/SSD1306_i2c_driver.c"
        "src/extflash_fs.c"
        "src/task_usb_storage_device.c"
        "src/task_gamepad_out.c"
        "src/tusb_descriptors.c"
        "src/task_display.c"
        "src/task_lua_vm.c"
        "src/gui_main.c"
        "src/lvgl_widgets/widget_horizontal_select.c"
        "src/task_input_manager.c"
        "src/button.c"

        "src/images/gear.c"

        "lua/lapi.c"
        "lua/lauxlib.c"
        "lua/lbaselib.c"
        "lua/lcode.c"
        "lua/lcorolib.c"
        "lua/lctype.c"
        "lua/ldblib.c"
        "lua/ldebug.c"
        "lua/ldo.c"
        "lua/ldump.c"
        "lua/lfunc.c"
        "lua/lgc.c"
        "lua/linit.c"
        "lua/liolib.c"
        "lua/llex.c"
        "lua/lmathlib.c"
        "lua/lmem.c"
        "lua/loadlib.c"
        "lua/lobject.c"
        "lua/lopcodes.c"
        "lua/loslib.c"
        "lua/lparser.c"
        "lua/lstate.c"
        "lua/lstring.c"
        "lua/lstrlib.c"
        "lua/ltable.c"
        "lua/ltablib.c"
        "lua/ltm.c"
        "lua/luac.c"
        "lua/lundump.c"
        "lua/lutf8lib.c"
        "lua/lvm.c"
        "lua/lzio.c"

    INCLUDE_DIRS
        "./include"
        "./include/lvgl_widgets"
        "../../../SHARED/include/"
        "./lua"

    EMBED_TXTFILES
        "assets/index.html"
        "assets/style.css"
    
    REQUIRES
        tinyusb
        esp_wifi
        nvs_flash
        spi_flash
        esp-tls
        esp_netif
        esp_http_server
        driver
)

